### ISSUE TITLE
Running consumer from the example giving an exception on german windows system.

### ISSUE THREAD

**Issue by srinivas-akula** [mapr-demos/kafka-sample-programs#1]
**new ProducerRecord<String, String>(
                        "fast-messages",
                        String.format("{\"type\":\"test\", \"t\":%.3f, \"k\":%d}", System.nanoTime() \* 1e-9, i)))**
%.3f places comma instead of pullstop.

Exception in thread "main" com.fasterxml.jackson.core.JsonParseException: Unexpected character ('8' (code 56)): was expecting double-quote to start field name
 at [Source: {"type":"test", "t":365269,820310, "k":0}; line: 1, column: 29]
        at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1419)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:508)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:437)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddName(ReaderBasedJsonParser.java:1340)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:618)
        at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:212)
        at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:62)
        at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:14)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3051)
        at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:1818)
        at com.mapr.examples.Consumer.main(Consumer.java:56)
        at com.mapr.examples.Run.main(Run.java:19)

**Comment by srinivas-akula** [comment]
Specially from command line

**Comment by tdunning** [comment]
Do you have a suggestion about how to fix this?

**Comment by srinivas-akula** [comment]
Yes, I know the reason behind this.
String.format() uses the default Locale from the system. (In my case it is DE).
So, I replaced String.format with custom method for formatting and it works as well :)

package com.mapr.examples;

import com.google.common.io.Resources;
import org.apache.kafka.clients.producer.KafkaProducer;
import org.apache.kafka.clients.producer.ProducerRecord;

import java.io.IOException;
import java.io.InputStream;
import java.util.Properties;

/**
- This producer will send a bunch of messages to topic "fast-messages". Every
- so often, it will send a message to "slow-messages". This shows how messages
- can be sent to multiple topics. On the receiving end, we will see both kinds
- of messages but will also see how the two topics aren't really synchronized.
  */
  public class Producer {
  
  public static void main(String[] args) throws IOException {
      // set up the producer
      KafkaProducer<String, String> producer;
      try (InputStream props = Resources.getResource("producer.props").openStream()) {
          Properties properties = new Properties();
          properties.load(props);
          producer = new KafkaProducer<>(properties);
      }
  
  ```
  try {
      String format;
      for (int i = 0; i < 1000000; i++) {
          format = format("test", i);
          // send lots of messages
          producer.send(new ProducerRecord<String, String>("fast-messages", format));
  
          // every so often send to a different topic
          if (i % 1000 == 0) {
  
              format = format("marker", i);
              producer.send(new ProducerRecord<String, String>("fast-messages", format));
  
              format = format("other", i);
              producer.send(new ProducerRecord<String, String>("summary-markers", format));
  
              producer.flush();
          }
  
      }
  } catch (Throwable throwable) {
      System.out.printf("%s", throwable.getStackTrace());
  } finally {
      producer.close();
  }
  ```
  
  }
  
  private static String format(String type, long i) {
      StringBuilder builder = new StringBuilder();
      builder.append("{\"type\":").append("\"").append(type).append("\"");
      builder.append(",\"t\":").append("\"").append(System.nanoTime() \* 1e-9).append("\"");
      builder.append(",\"k\":").append("\"").append(i).append("\"").append("}");
      final String format = builder.toString();
      System.out.println(i + " Format: " + format);
      return format;
  }
  }

**Comment by srinivas-akula** [comment]
You can check and can close the issue.
